### ISSUE TITLE
[APERO] Multiprocess error ForkAwareLocal

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-drs#705]
Weird error when running nirps_ha_offline

```
Process Process-15705:
Traceback (most recent call last):
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cosmos99/nirps/git-bin/apero-drs-offline/apero/tools/module/processing/drs_processing.py", line 2540, in _linear_process
    return_dict[priority] = pp
  File "<string>", line 2, in __setitem__
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-15704:
Traceback (most recent call last):
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cosmos99/nirps/git-bin/apero-drs-offline/apero/tools/module/processing/drs_processing.py", line 2540, in _linear_process
    return_dict[priority] = pp
  File "<string>", line 2, in __setitem__
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by njcuk9999** [comment]
This might have just been a Ctrl+C event. Closing for now.
