### ISSUE TITLE
issue adding objects in objdb

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#710]
18:48:06.742-**|ASTROM| ***************************************************************************
18:48:06.762-**|ASTROM| Updating pending-list online database
18:48:06.784-**|ASTROM| ***************************************************************************
18:48:09.454-  |ASTROM| Adding OBJECT=TOI1442 to dataframe
```
18:48:09.475-!!|ASTROM| E[01-010-00001]: Unhandled error has occurred: Error <class 'AttributeError'>
18:48:09.475-!!|ASTROM| 
18:48:09.475-!!|ASTROM| Traceback (most recent call last):
18:48:09.476-!!|ASTROM|  File "/apero/apero-drs/apero/core/utils/drs_startup.py", line 432, in run
18:48:09.476-!!|ASTROM|    llmain = func(recipe, params)
18:48:09.476-!!|ASTROM|  File "/apero/apero-drs/tools/bin/apero_astrometrics.py", line 195, in __main__
18:48:09.476-!!|ASTROM|    drs_astrometrics.add_obj_to_sheet(params, add_objs)
18:48:09.477-!!|ASTROM|  File "/apero/apero-drs/apero/tools/module/database/drs_astrometrics.py", line 1155, in add_obj_to_sheet
18:48:09.477-!!|ASTROM|    dataframe = dataframe.append(astro_obj.to_dataframe())
18:48:09.477-!!|ASTROM|  File "/conda/miniconda3/envs/apero-env/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
18:48:09.477-!!|ASTROM|    return object.__getattribute__(self, name)
18:48:09.477-!!|ASTROM| AttributeError: 'DataFrame' object has no attribute 'append'
18:48:09.478-!!|ASTROM| 
18:48:09.696-**|ASTROM| ***************************************************************************
18:48:09.721-@!|ASTROM| W[40-003-00005]: Recipe apero_astrometrics has NOT been successfully completed
18:48:09.744-**|ASTROM| ***************************************************************************
```
 offline Wed Aug 16 08:48:10 spdrs@apikipiha: /data/spirou4/apero-data/offline/runs

**Comment by larnoldgithub** [comment]
I've tried killing my screen and re-launching the python env for the DRS, but it didn't help.

**Comment by njcuk9999** [comment]
Hi Luc,

Sorry about this, this is due to an update with pandas, I already fixed this in v0.7.287 but you can't use that version yet.

I'll add this update to the v0.7.286-stable-test.

**Comment by njcuk9999** [comment]
Do a git pull now and it should work.
