### ISSUE TITLE
update reduction with a new run: crashing

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#735]
Here's the last command I see after I launched the update to the v288 full processing with a few more nights: 

22:03:22.293-@!|PROC|   apero_pol_spirou.py 2023-11-02 --exposures 2921141o_pp_e2dsff_tcorr_AB.fits 2921142o_pp_e2dsff_tcorr_AB.fits 2921143o_pp_e2dsff_tcorr_AB.fits 2921144o_pp_e2dsff_tcorr_AB.fits --crunfile=complete_run_custom.ini --program=POLAR[07321] --recipe_kind=polar-tcorr --shortname=POLAR --parallel=True
22:03:22.300-  |PROC| ***************************************************************************

And the error I got:

 Traceback (most recent call last):
  File "/Users/moutou/apero-drs/apero/core/utils/drs_startup.py", line 433, in run
    llmain = func(recipe, params)
  File "/Users/moutou/apero-drs/apero/recipes/spirou/apero_pol_spirou.py", line 158, in __main__
    pprops = gen_pol.calculate_continuum(params, recipe, pprops)
  File "/Users/moutou/apero-drs/apero/science/polar/gen_pol.py", line 1412, in calculate_continuum
    contflux = _fit_continuum(params, recipe, wldata, stokes_i,
  File "/Users/moutou/apero-drs/apero/science/polar/gen_pol.py", line 2600, in _fit_continuum
    spl = interpolate.splrep(wavemap[mspec], spec[mspec], k=3,
  File "/Users/moutou/miniconda3/envs/ap288/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 288, in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
  File "/Users/moutou/miniconda3/envs/ap288/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 508, in splrep
    raise _iermess[ier][1](_iermess[ier][0])
 ValueError: Error on input data

And indeed, the polar products are not done, for this sequence.
Has someone seen this error ?

**Comment by larnoldgithub** [comment]
Same as what I got in #727 ?

**Comment by clairem789** [comment]
Yes indeed it's the same error, it's the first time I see it but apparently it was here before as well. I got 144 entries of this command in msg/tool/other/: grep _iermess *log|wc -l
@larnoldgithub Did you find a way to fix it? (not much on #727)

**Comment by larnoldgithub** [comment]
sorry I've nothing in my notes. I think it's mostly for low snr OG -although QC are ok-, but I'm not sure.

**Comment by larnoldgithub** [comment]
and the exemple you report is again for a faint object/low snr.
