### ISSUE TITLE
[SPIROU] polar code error - Error on input data

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-drs#761]
Happens quite often on `spirou_offline`

```
08:48:48.518-  |PROC| ***************************************************************************
08:48:48.524-@!|PROC|W[40-503-00019]: Error found for ID='42949'
08:48:48.530-@!|PROC|	apero_pol_spirou.py 2023-07-24 --exposures 2886220o_pp_e2dsff_tcorr_AB.fits 2886221o_pp_e2dsff_tcorr_AB.fits 2886222o_pp_e2dsff_tcorr_AB.fits 2886223o_pp_e2dsff_tcorr_AB.fits --crunfile=toi2120_rerun.ini --program=POLAR[42949] --recipe_kind=polar-tcorr --shortname=POLAR --parallel=True
08:48:48.536-  |PROC| ***************************************************************************
08:48:48.542-  |PROC|
 E[01-010-00001]: Unhandled error has occurred: Error <class 'ValueError'>
 
 Traceback (most recent call last):
  File "/cosmos99/spirou/apero-bin/apero-drs/apero/core/utils/drs_startup.py", line 433, in run
    llmain = func(recipe, params)
  File "/cosmos99/spirou/apero-bin/apero-drs/apero/recipes/spirou/apero_pol_spirou.py", line 158, in __main__
    pprops = gen_pol.calculate_continuum(params, recipe, pprops)
  File "/cosmos99/spirou/apero-bin/apero-drs/apero/science/polar/gen_pol.py", line 1447, in calculate_continuum
    contpol = _fit_continuum(params, recipe, wldata, pol,
  File "/cosmos99/spirou/apero-bin/apero-drs/apero/science/polar/gen_pol.py", line 2593, in _fit_continuum
    spl = interpolate.splrep(wavemap[mspec], spec[mspec], k=3,
  File "/cosmos99/spirou/bin/miniconda3/envs/apero-env-07/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 288, in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
  File "/cosmos99/spirou/bin/miniconda3/envs/apero-env-07/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 508, in splrep
    raise _iermess[ier][1](_iermess[ier][0])
 ValueError: Error on input data
```

**Comment by njcuk9999** [comment]
Running again seems to fix this problem... closed for now.
