### ISSUE TITLE
0.7.289  error with apero_reject.py

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#774]
I'm in conda with the correct env

apero_reject.py --identifier=3036019 --autofill="1,1,1,CALIB_aborted_dark_24BQ03-Aug15"

gives the error:

```
04:31:33.272-!!|REJECT| E[01-010-00001]: Unhandled error has occurred: Error <class 'AttributeError'>
04:31:33.273-!!|REJECT| 
04:31:33.273-!!|REJECT| Traceback (most recent call last):
04:31:33.273-!!|REJECT|  File "/apero/apero-drs/apero/core/utils/drs_startup.py", line 433, in run
04:31:33.273-!!|REJECT|    llmain = func(recipe, params)
04:31:33.274-!!|REJECT|  File "/apero/apero-drs/tools/bin/apero_reject.py", line 111, in __main__
04:31:33.274-!!|REJECT|    drs_reject.add_file_reject(params, identifier)
04:31:33.274-!!|REJECT|  File "/apero/apero-drs/apero/tools/module/listing/drs_reject.py", line 69, in add_file_reject
04:31:33.274-!!|REJECT|    google_sheet = gspd.spread.Spread(sheet_id)
04:31:33.274-!!|REJECT|  File "/conda/miniconda3/envs/apero-env/lib/python3.9/site-packages/gspread_pandas/spread.py", line 126, in __init__
04:31:33.274-!!|REJECT|    self.client = Client(user, config, scope, creds)
04:31:33.275-!!|REJECT|  File "/conda/miniconda3/envs/apero-env/lib/python3.9/site-packages/gspread_pandas/client.py", line 96, in __init__
04:31:33.275-!!|REJECT|    self._root = self._drive_request(file_id="root", params={"fields": "name,id"})
04:31:33.275-!!|REJECT|  File "/conda/miniconda3/envs/apero-env/lib/python3.9/site-packages/gspread_pandas/client.py", line 197, in _drive_request
04:31:33.275-!!|REJECT|    res = self.request(method, url, params=params, json=data)
04:31:33.275-!!|REJECT|  File "/conda/miniconda3/envs/apero-env/lib/python3.9/site-packages/gspread_pandas/util.py", line 292, in request
04:31:33.276-!!|REJECT|    return ClientV4.request(client, *args, **kwargs)
04:31:33.276-!!|REJECT| AttributeError: type object 'Client' has no attribute 'request'
04:31:33.276-!!|REJECT| 
04:31:33.292-**|REJECT| ***************************************************************************
04:31:33.299-@!|REJECT| W[40-003-00005]: Recipe apero_reject has NOT been successfully completed
04:31:33.305-**|REJECT| ***************************************************************************
```

**Comment by njcuk9999** [comment]
This seems to be the same error you had in March (Issue #758) did you fix it then?
It was also a bug that @aleciane had in June (Issue #765) I'm not sure if that was resolved?

I wasn't able to reproduce it either time.

**Comment by njcuk9999** [comment]
So I've been looking into this.... it may be somehow you have installed a module that has updated `gspread` (we require a module called `gspread_pandas` to be 3.2.2  but it seems most my systems are on `gspread=5.X.X`  and `gspread-pandas==3.2.2` 

It seems in the newest version of `gspread` this "Client" class has no method "request" - that was there in the older versions.

Then I found this: https://github.com/aiguofer/gspread-pandas/pull/101   which specifically states that gspread-pandas must be :
| gspread>=5.0.0, <6



So I think the solution is to do: 
```
pip install --force-reinstall "gspread==5.12.4"
```

and try again. 

I'll add a line to the requirements to check `gspread` as well as `gspread_pandas`

**Comment by larnoldgithub** [comment]
updating gsspread allowed me to reject that odometer successfully, same command that above:

but at the end of install of the package I got
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lbl 0.63.13 requires requests==2.28.2, but you have requests 2.32.3 which is incompatible.
```

**Comment by larnoldgithub** [comment]
Full log of the terminal:

```
pip install --force-reinstall "gspread==5.12.4"
Collecting gspread==5.12.4
  Downloading gspread-5.12.4-py3-none-any.whl.metadata (8.8 kB)
Collecting google-auth>=1.12.0 (from gspread==5.12.4)
  Using cached google_auth-2.33.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting google-auth-oauthlib>=0.4.1 (from gspread==5.12.4)
  Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth>=1.12.0->gspread==5.12.4)
  Using cached cachetools-5.4.0-py3-none-any.whl.metadata (5.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.12.0->gspread==5.12.4)
  Using cached pyasn1_modules-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=1.12.0->gspread==5.12.4)
  Using cached rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread==5.12.4)
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Collecting requests>=2.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Downloading urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==5.12.4)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Downloading gspread-5.12.4-py3-none-any.whl (49 kB)
Using cached google_auth-2.33.0-py2.py3-none-any.whl (200 kB)
Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)
Using cached cachetools-5.4.0-py3-none-any.whl (9.5 kB)
Using cached pyasn1_modules-0.4.0-py3-none-any.whl (181 kB)
Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Using cached rsa-4.9-py3-none-any.whl (34 kB)
Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Using cached pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Downloading urllib3-2.2.2-py3-none-any.whl (121 kB)
Installing collected packages: urllib3, pyasn1, oauthlib, idna, charset-normalizer, certifi, cachetools, rsa, requests, pyasn1-modules, requests-oauthlib, google-auth, google-auth-oauthlib, gspread
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.19
    Uninstalling urllib3-1.26.19:
      Successfully uninstalled urllib3-1.26.19
  Attempting uninstall: pyasn1
    Found existing installation: pyasn1 0.6.0
    Uninstalling pyasn1-0.6.0:
      Successfully uninstalled pyasn1-0.6.0
  Attempting uninstall: oauthlib
    Found existing installation: oauthlib 3.2.2
    Uninstalling oauthlib-3.2.2:
      Successfully uninstalled oauthlib-3.2.2
  Attempting uninstall: idna
    Found existing installation: idna 3.7
    Uninstalling idna-3.7:
      Successfully uninstalled idna-3.7
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.3.2
    Uninstalling charset-normalizer-3.3.2:
      Successfully uninstalled charset-normalizer-3.3.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.7.4
    Uninstalling certifi-2024.7.4:
      Successfully uninstalled certifi-2024.7.4
  Attempting uninstall: cachetools
    Found existing installation: cachetools 5.4.0
    Uninstalling cachetools-5.4.0:
      Successfully uninstalled cachetools-5.4.0
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9
    Uninstalling rsa-4.9:
      Successfully uninstalled rsa-4.9
  Attempting uninstall: requests
    Found existing installation: requests 2.28.2
    Uninstalling requests-2.28.2:
      Successfully uninstalled requests-2.28.2
  Attempting uninstall: pyasn1-modules
    Found existing installation: pyasn1_modules 0.4.0
    Uninstalling pyasn1_modules-0.4.0:
      Successfully uninstalled pyasn1_modules-0.4.0
  Attempting uninstall: requests-oauthlib
    Found existing installation: requests-oauthlib 2.0.0
    Uninstalling requests-oauthlib-2.0.0:
      Successfully uninstalled requests-oauthlib-2.0.0
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.33.0
    Uninstalling google-auth-2.33.0:
      Successfully uninstalled google-auth-2.33.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 1.2.1
    Uninstalling google-auth-oauthlib-1.2.1:
      Successfully uninstalled google-auth-oauthlib-1.2.1
  Attempting uninstall: gspread
    Found existing installation: gspread 6.1.2
    Uninstalling gspread-6.1.2:
      Successfully uninstalled gspread-6.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lbl 0.63.13 requires requests==2.28.2, but you have requests 2.32.3 which is incompatible.
Successfully installed cachetools-5.4.0 certifi-2024.7.4 charset-normalizer-3.3.2 google-auth-2.33.0 google-auth-oauthlib-1.2.1 gspread-5.12.4 idna-3.7 oauthlib-3.2.2 pyasn1-0.6.0 pyasn1-modules-0.4.0 requests-2.32.3 requests-oauthlib-2.0.0 rsa-4.9 urllib3-2.2.2

```

**Comment by larnoldgithub** [comment]
> This seems to be the same error you had in March (Issue #758) did you fix it then? It was also a bug that @aleciane had in June (Issue #765) I'm not sure if that was resolved?
> 
> I wasn't able to reproduce it either time.

No I didn't fix it then, but it seems to work now with
apero_reject.py --objname="MATTTEST"
although  Apero reports it's already in the reject list. No errors though.
